name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Create a directory for the new package
            mkdir -p /home/${{ vars.EC2_USERNAME }}/${{github.event.repository.name}}
            scp -i ${{ secrets.EC2_KEY }} . ${{ vars.EC2_USERNAME }}@${{ vars.EC2_HOST }}:/home/${{ vars.EC2_USERNAME }}/${{github.event.repository.name}}
            pip3 install -r /home/${{ vars.EC2_USERNAME }}/${{github.event.repository.name}}/requirements.txt
            # Run the Flask app
            FLASK_APP=/home/${{ vars.EC2_USERNAME }}/${{github.event.repository.name}}/app.py flask run --host=0.0.0.0 --port=5000
            # Remove the old package
